# flake8: noqa

"""
    Dyspatch API

    # Introduction  The Dyspatch API is based on the REST paradigm, and features resource based URLs with standard HTTP response codes to indicate errors. We use standard HTTP authentication and request verbs, and all responses are JSON formatted. See our [Implementation Guide](https://docs.dyspatch.io/development/implementing_dyspatch/) for more details on how to implement Dyspatch.  ## API Client Libraries Dyspatch provides API Clients for popular languages and web frameworks.  - [Java](https://github.com/getdyspatch/dyspatch-java) - [Javascript](https://github.com/getdyspatch/dyspatch-javascript) - [Python](https://github.com/getdyspatch/dyspatch-python) - [C#](https://github.com/getdyspatch/dyspatch-dotnet) - [Go](https://github.com/getdyspatch/dyspatch-golang) - [Ruby](https://github.com/getdyspatch/dyspatch-ruby)   # noqa: E501

    The version of the OpenAPI document: 2020.11
    Contact: support@dyspatch.io
    Generated by: https://openapi-generator.tech
"""


__version__ = "6.0.0"

# import ApiClient
from dyspatch_client.api_client import ApiClient

# import Configuration
from dyspatch_client.configuration import Configuration

# import exceptions
from dyspatch_client.exceptions import OpenApiException
from dyspatch_client.exceptions import ApiAttributeError
from dyspatch_client.exceptions import ApiTypeError
from dyspatch_client.exceptions import ApiValueError
from dyspatch_client.exceptions import ApiKeyError
from dyspatch_client.exceptions import ApiException
